config/routes.rb
Guaguale::Application.routes.draw do
  
  namespace :api do 
    namespace :v1 do
      resources :tickets, :only => :index
    end
  end
  
  devise_for :customers, :path => 'merc', 
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :controllers => { :registrations => "customers/registrations",  
                               :sessions => 'customers/sessions' }  
  match '/merc/edit' => 'customers/passwords#edit', :as => 'edit_merc', :via => :get
  
  devise_for :users, 
             :path => 'account', 
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :controllers => { :registrations => "users/registrations",
                               :sessions => 'users/sessions' }
  
    
  root :to => redirect('/account/login')
  
  match '/merc' => redirect('/merc/login'), :as => 'merc'
  # match '/merc/dashboard' => 'customers#dashboard', :as => 'dashboard'
  
  namespace :dashboard do
    root to:'customers#index'
    
    match 'tickets/active' => 'tickets#active', :via => :put, :as => :active_ticket
    
    resources :tickets do
      get 'actived', :on => :collection
    end
  end
  
  namespace :cpanel do
    
    root to:'home#index'
    
    resources :tickets do 
      collection do
        get 'search'
      end
      
    end
    resources :customers
  end
  
  # mount Resque::Server, :at => '/resque'

end

app/models/ticket.rb
# coding: utf-8
class Ticket < ActiveRecord::Base
  attr_accessible :expire_end_at, :expire_start_at, :avatar, :customer_id
  
  has_attached_file :avatar, :styles => { :large  => "600x600>",
                                          :medium => "300x300>", 
                                          :small  => "150x150>",
                                          :thumb  => "50x50>" }#,
                                          # :path => ":rails_root/files/:id/:style/:filename",
                                          # :url => "/files/:id/:style"
                                          
  validates_attachment :avatar, presence: true,
                                content_type: { content_type: ["image/jpeg","image/png","image/gif"] },
                                size: { in: 0..300.kilobytes }
  
  validates :expire_end_at, presence: true
  validates :expire_start_at, presence: true
  
  belongs_to :customer
  
  before_save :create_token   
  
  scope :actived, where(:active => true)   
  scope :unactive, where(:active => false)                                              
  
  
  def self.search(search)
    if search
      joins(:customer).where('customers.name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
  def state
    active? ? '已消费' : '未消费'
  end
  
  def as_json(options={})
    # super({:only => [:id, :token, :expire_start_at, :expire_end_at]})
    # .merge(thumb_image_url: avatar.url(:small), release_on: created_at.to_date)
    {
      :id => id, 
      :token => token, 
      :expire_start_at => expire_start_at, 
      :expire_end_at => expire_end_at,
      :release_on => created_at.to_date,
      :thumb_image_url => avatar.url(:small),
      :large_image_url => avatar.url(:medium)
    }
  end
  
  private 
  
  def create_token
    if new_record?
      array = []
      12.times do 
        array << rand(9) + 1
      end
      self.token = array.join('')
    end
  end
  
end

app/controllers/api/v1/tickets_controller.rb
module Api
  module V1
    class TicketsController < ApplicationController
      
      respond_to :json
      
      def index
        
        offset = params[:offset] || 3
        @tickets = Ticket.unactive.order("RAND()").uniq.limit(offset)
        
        respond_with(@tickets)
        
      end
      
    end
  end
end

app/controllers/cpanel/base_controller.rb
class Cpanel::BaseController < ApplicationController
  before_filter :authenticate_user!
  
  layout "cpanel"
end

app/controllers/cpanel/customers_controller.rb
# coding:utf-8
class Cpanel::CustomersController < Cpanel::BaseController
  before_filter :find_customer, only: [:edit, :show, :update, :destroy]
  def index
    @customers = Customer.paginate(:page => params[:page], :per_page => 6)
  end
  
  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params[:customer])
    if @customer.save
      CustomerMailer.customer_notify_email(@customer).deliver
      flash[:success] = "添加商家成功！商家登录密码：#{@customer.password}"
      redirect_to cpanel_customers_url
    else
      render 'new'
    end
    
  end
  
  def edit
    
  end
  
  def update
    if @customer.update_attributes(params[:customer])
      flash[:success] = "商家资料更新成功."
      redirect_to cpanel_customers_url
    else
      render :edit
    end
    
  end
  
  def destroy
    @customer.destroy
    flash[:success] = '商家删除成功.'
    redirect_to cpanel_customers_url
  end
  
  private 
  
  def find_customer
    @customer = Customer.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "未找到该记录."
    redirect_to cpanel_customers_url
  end
  
end

app/controllers/cpanel/home_controller.rb
class Cpanel::HomeController < Cpanel::BaseController
  def index
    # redirect_to cpanel_tickets_path
    # return
  end
end

app/controllers/cpanel/tickets_controller.rb
# encoding:utf-8
class Cpanel::TicketsController < Cpanel::BaseController
  
  load_and_authorize_resource
  
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
  def index
    @tickets = Ticket.order("created_at desc").includes(:customer).
      paginate(page: params[:page], per_page: 5)
  end
  
  def show
  end
  def new
    @ticket = Ticket.new
  end
  
  def search
    @tickets = Ticket.order("created_at desc")
                     .search(params[:search])
                     .paginate(:page => params[:page], :per_page => 5)
    render :action => 'index'
  end

  def edit
  end
  
  def create
    @ticket = Ticket.new(params[:ticket])
    if @ticket.save
      flash[:success] = '奖券添加成功!!!'
      redirect_to cpanel_tickets_url 
    else
      render "new"
    end
  end
  
  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:success] = '奖券更新成功!!!'
      redirect_to cpanel_tickets_url
    else
      render "edit"
    end
  end
  
  def destroy
    
    @ticket.destroy
    flash[:success] = "奖券删除成功!!!"
    redirect_to cpanel_tickets_url
  end
  
  private 
  
  def find_ticket
    @ticket = Ticket.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "奖券没有找到!!!"
    redirect_to cpanel_tickets_url
  end
end

app/controllers/dashboard/tickets_controller.rb
# coding: utf-8
class Dashboard::TicketsController < ApplicationController
  before_filter :authenticate_customer!
  
  layout 'customer'
  
  def actived
    @tickets = current_customer.tickets.actived.paginate(:page => params[:page],
                                                         :per_page => 5)
  end
  
  def active
    @ticket = current_customer.tickets.find_by_token(params[:ticket][:token])
    
    msg = {}
    
    if @ticket
      if @ticket.active
        msg[:info] = '奖券已经激活，赶快去消费吧！！！'
      else
        if @ticket.expire_end_at.to_date < Time.now.to_date
          msg[:notice] = '奖券已过期'
        else
          if @ticket.update_attribute('active',true)
            msg[:success] = '奖券激活成功'
          else
            msg[:error] = '奖券激活失败，请重试。'
          end
        end
      end
    else
      msg[:error] = '没有找到相关的奖券'
    end
    
    flash[:message] = msg
    redirect_to dashboard_root_path
  end
  
end

app/controllers/tickets_controller.rb
# encoding:utf-8
class TicketsController < ApplicationController
  
  def active
    
  end
  
  def verify
  end
  
end

app/helpers/cpanel/base_helper.rb
module Cpanel::BaseHelper
end

app/helpers/cpanel/customers_helper.rb
module Cpanel::CustomersHelper
end

app/helpers/cpanel/home_helper.rb
module Cpanel::HomeHelper
end

app/helpers/cpanel/tickets_helper.rb
module Cpanel::TicketsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/cpanel/tickets/_fields.html.erb
	<%= f.label :expire_start_at, "有效期开始日", class:"control-label" %>
	<div class="controls">
		<%= f.text_field 'expire_start_at', value: "#{Date.today}", class:"datepicker" %>
	</div>
	
	<%= f.label :expire_start_at, "有效期截止日", class:"control-label" %>
	<div class="controls">
		<%= f.text_field 'expire_end_at', value: "#{Date.today + 1}", class:"datepicker" %>
	</div>
	
	<%= f.label :customer_id, '商家名称', class:"control-label" %>
	<div class="controls">
		<% if Customer.all.size > 0 %>
		<%= f.collection_select :customer_id, Customer.all, :id, :comp_name %>
		<% else %>
			<%= link_to '添加一个商家', new_cpanel_customer_path, class:"btn btn-primary" %>
		<% end %>
	</div>
	
	<%= f.label :avatar, "上传奖券图片", class:"control-label" %>
	<div class="controls">
	<% unless f.object.new_record? %>
		<%= image_tag(@ticket.avatar.url(:small), width:100, class:"avatar") %>
	<% end %>
	<%= f.file_field :avatar %>
	</div>
</div>

app/views/cpanel/tickets/_form.html.erb
<div class="row">
	<div class="span9 well">
		<%= form_for([:cpanel, @ticket], :html => { :multipart => true,
			 																class:"form-horizontal" }) do |f| %>
			<%= render "shared/error_messages", :target => @ticket %>
			<fieldset>
				<legend><%= legend %></legend>
				<div class="control-group">
				<%= render 'fields', :f => f %>
				<div class="controls">
				<%= f.submit submit_value, class: "btn btn-primary", :disable_with => "正在提交..." %>
				<!-- <a href="javascript:history.go(-1)" class="btn">返回</a> -->
				<%= link_to '返回', cpanel_tickets_path, class:"btn" %>
				</div>
				</div>
			</fieldset>
		
		<% end %>
	</div>
</div>

app/views/cpanel/tickets/_search_form.html.erb
<%= form_tag search_cpanel_tickets_path, :method => 'get', class:"form-search well" do  %>
	<%= text_field_tag :search, params[:search], class: "search-query", placeholder:"输入商家名" %>
	<button type="submit" class="btn"><i class="icon-search"></i> 搜索</button>
<% end %>

app/views/cpanel/tickets/edit.html.erb
<%= render :partial => 'form', :locals => { :legend => '更新奖券信息',
																						:submit_value => '更新奖券'} %>

app/views/cpanel/tickets/index.html.erb
<div class="page-header">
	<h2>所有的奖券</h2>
</div>
	
<%= render 'search_form' %>
	
<%= render 'layouts/pager' %>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>消费码</th>
			<th>广告图片</th>
			<th>商家名称</th>
			<th>有效期开始日</th>
			<th>有效期截止日</th>
			<th>奖券添加日期</th>
			<th>是否消费</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @tickets.each do |ticket| %>
			<tr>
				<td><%= link_to ticket.id, [:cpanel, ticket] %></td>
				<td><%= ticket.token %></td>
				<td>
					<% if ticket.avatar.exists? %>
						<%= image_tag(ticket.avatar.url(:thumb)) %>
					<% end %>
				</td>
				<td><%= ticket.customer.comp_name if ticket.customer.present? %></td>
				<td><%= ticket.expire_start_at %></td>
				<td><%= ticket.expire_end_at %></td>
				<td><%= ticket.created_at %></td>
				<td><%= ticket.state %></td>
				<td>
					<%= link_to "编辑", edit_cpanel_ticket_path(ticket), class:"btn btn-mini" %>
					<%= link_to "删除", [:cpanel, ticket], class:"btn btn-mini btn-danger", 
														:method => :delete,
														:confirm => "确定要删除吗？" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= render 'layouts/pager' %>

app/views/cpanel/tickets/new.html.erb
<%= render :partial => 'form', :locals => { :legend => '请输入奖券信息',
																						:submit_value => '添加一个新奖券'} %>

app/views/cpanel/tickets/show.html.erb
<div class="page-header">
	<h1>#<%= @ticket.id %>-奖券的详细信息</h1>
</div>

<div class="span6">
	<div class="pull-left"><%= image_tag(@ticket.avatar.url(:medium)) %></div>
	<div class="ticket-detail-info offset3">
		<p><span class="t">消费码:</span> <%= @ticket.token %></p>
		<p><span>有效期开始日:</span> <%= @ticket.expire_start_at %></p>
		<p class="last-p"><span>有效期截止日:</span> <%= @ticket.expire_end_at %></p>
		<div><a href="javascript:history.go(-1)" class="btn">返回</a></div>
	</div>
</div>