config/routes.rb
Guaguale::Application.routes.draw do
  
  namespace :api do 
    namespace :v1 do
      resources :tickets, :only => :index
    end
  end
  
  devise_for :customers, :path => 'merc', 
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :controllers => { :registrations => "customers/registrations",  
                               :sessions => 'customers/sessions' }  
  match '/merc/edit' => 'customers/passwords#edit', :as => 'edit_merc', :via => :get
  
  devise_for :users, 
             :path => 'account', 
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :controllers => { :registrations => "users/registrations",
                               :sessions => 'users/sessions' }
  
    
  root :to => redirect('/account/login')
  
  match '/merc' => redirect('/merc/login'), :as => 'merc'
  # match '/merc/dashboard' => 'customers#dashboard', :as => 'dashboard'
  
  namespace :dashboard do
    root to:'customers#index'
    
    match 'tickets/active' => 'tickets#active', :via => :put, :as => :active_ticket
    
    resources :tickets do
      get 'actived', :on => :collection
    end
  end
  
  namespace :cpanel do
    
    root to:'home#index'
    
    resources :tickets do 
      collection do
        get 'search'
      end
      
    end
    resources :customers
  end
  
  # mount Resque::Server, :at => '/resque'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:tel]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :tel, :address, :comp_name,
                  :info, :email,  :remember_me, :password, :password_confirmation
  # attr_accessible :title, :body
  
  default_scope :order => 'created_at DESC'
  
  TELPATTERN = /^0{0,1}(13[0-9]|147|15[5-9]|15[0-3]|18[5-9]|180|182)[0-9]{8}$/
  
  validates :name, presence: true
  validates :tel, presence: true, format: { with:TELPATTERN }, uniqueness: true
  validates :comp_name, presence: true
  validates :info, presence: true
  validates :address, presence: true
  
  has_many :tickets, :dependent => :destroy
  
  before_validation :set_default_password
  
  private
  
  def set_default_password
    if new_record?
      generated_password = Devise.friendly_token.first(6)
      self.password = generated_password
      self.password_confirmation = generated_password
    end
  end
  
end

app/controllers/cpanel/customers_controller.rb
# coding:utf-8
class Cpanel::CustomersController < Cpanel::BaseController
  before_filter :find_customer, only: [:edit, :show, :update, :destroy]
  def index
    @customers = Customer.paginate(:page => params[:page], :per_page => 6)
  end
  
  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params[:customer])
    if @customer.save
      CustomerMailer.customer_notify_email(@customer).deliver
      flash[:success] = "添加商家成功！商家登录密码：#{@customer.password}"
      redirect_to cpanel_customers_url
    else
      render 'new'
    end
    
  end
  
  def edit
    
  end
  
  def update
    if @customer.update_attributes(params[:customer])
      flash[:success] = "商家资料更新成功."
      redirect_to cpanel_customers_url
    else
      render :edit
    end
    
  end
  
  def destroy
    @customer.destroy
    flash[:success] = '商家删除成功.'
    redirect_to cpanel_customers_url
  end
  
  private 
  
  def find_customer
    @customer = Customer.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "未找到该记录."
    redirect_to cpanel_customers_url
  end
  
end

app/controllers/customers/passwords_controller.rb
# encoding:utf-8
class Customers::PasswordsController < ApplicationController
  before_filter :authenticate_customer!
  layout 'customer'
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    
    if @customer.update_with_password(params[:customer])
      sign_in(@customer, :bypass => true)
      flash[:notice] = "密码修改成功."
      redirect_to dashboard_active_path
    else
      render :edit 
    end
  end
  
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
  layout 'customer'
  
  protected
  
  def after_update_path_for(resource)
    dashboard_active_url
  end
  
end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
  layout 'merc_login'
  
  def after_sign_in_path_for(resource)
    if current_customer
      stored_location_for(resource) || dashboard_root_path
    else
      merc_path
    end
  end
  
  def after_sign_out_path_for(resource)
    merc_path
  end
  
end

app/controllers/dashboard/customers_controller.rb
# encoding:utf-8
class Dashboard::CustomersController < ApplicationController
  layout 'customer'
  
  before_filter :authenticate_customer!, except:[:home]
  
  def home
    
  end
  
  def active
  end
  
  def verify
    @ticket = current_customer.tickets.find_by_token(params[:ticket][:token])
    
    msg = {}
    
    if @ticket
      if @ticket.active
        msg[:info] = '奖券已经激活，赶快去消费吧！！！'
      else
        if @ticket.expire_end_at.to_date < Time.now.to_date
          msg[:notice] = '奖券已过期'
        else
          if @ticket.update_attribute('active',true)
            msg[:success] = '奖券激活成功'
          else
            msg[:error] = '奖券激活失败，请重试。'
          end
        end
      end
    else
      msg[:error] = '没有找到相关的奖券'
    end
    
    flash[:message] = msg
    redirect_to :action => 'active'
  end
  
  def actived_tickets
    @tickets = current_customer.tickets.actived.paginate(:page => params[:page],
                              :per_page => 5)
  end
  
end

app/controllers/dashboard/tickets_controller.rb
# coding: utf-8
class Dashboard::TicketsController < ApplicationController
  before_filter :authenticate_customer!
  
  layout 'customer'
  
  def actived
    @tickets = current_customer.tickets.actived.paginate(:page => params[:page],
                                                         :per_page => 5)
  end
  
  def active
    @ticket = current_customer.tickets.find_by_token(params[:ticket][:token])
    
    msg = {}
    
    if @ticket
      if @ticket.active
        msg[:info] = '奖券已经激活，赶快去消费吧！！！'
      else
        if @ticket.expire_end_at.to_date < Time.now.to_date
          msg[:notice] = '奖券已过期'
        else
          if @ticket.update_attribute('active',true)
            msg[:success] = '奖券激活成功'
          else
            msg[:error] = '奖券激活失败，请重试。'
          end
        end
      end
    else
      msg[:error] = '没有找到相关的奖券'
    end
    
    flash[:message] = msg
    redirect_to dashboard_root_path
  end
  
end

app/helpers/cpanel/customers_helper.rb
module Cpanel::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def resource_name
      :customer
    end

    def resource
      @resource ||= Customer.new
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:customer]
    end
end

app/views/dashboard/customers/active.html.erb
<div class="well">
	<h2 class="page-header">验证刮刮券</h2>
	
	<%= form_for(:ticket, :url => dashboard_verify_path, :html => { :method => :put, :class => 'offset1 form-horizontal' }) do |f| %>
		<div class="control-group">
			<%= f.label :token, "输入消费码", class:'control-label' %>
			<div class="controls">
				<%= f.text_field :token, class:'span3' %>
			</div>
			<div class="controls">
				<%= f.submit '  消费  ', class:'btn btn-success btn-large btn-primary' %>
			</div>
		</div>
		
	<% end %>
	
	<br />
	<br />
	
	<% if flash[:message] %>
	<% flash[:message].each do |key, value| %>
	<div class="alert alert-block alert-<%= key %>">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <strong><%= value %></strong>
	</div>
	<% end %>
	<% end %>
	
</div>

app/views/dashboard/customers/actived_tickets.html.erb
<div class="well">
	
<h2 class="page-header">已经消费的奖券</h2>

<%= will_paginate @tickets %>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>消费码</th>
			<th>广告图片</th>
			<th>有效期开始日</th>
			<th>有效期截止日</th>
			<th>奖券添加日期</th>
		</tr>
	</thead>
	<tbody>
		<% @tickets.each do |ticket| %>
			<tr>
				<td><%= ticket.id %></td>
				<td><%= ticket.token %></td>
				<td>
					<% if ticket.avatar.exists? %>
						<%= image_tag(ticket.avatar.url(:thumb)) %>
					<% end %>
				</td>
				<td><%= ticket.expire_start_at %></td>
				<td><%= ticket.expire_end_at %></td>
				<td><%= ticket.created_at %></td>
			</tr>
		<% end %>
	</tbody>
</table>

</div>

app/views/dashboard/customers/index.html.erb
<div class="well">
	<h2 class="page-header">验证刮刮券</h2>
	
	<%= form_for(:ticket, :url => dashboard_active_ticket_path, :html => { :method => :put, :class => 'offset1 form-horizontal' }) do |f| %>
		<div class="control-group">
			<%= f.label :token, "输入消费码", class:'control-label' %>
			<div class="controls">
				<%= f.text_field :token, class:'span3' %>
			</div>
			<div class="controls">
				<%= f.submit '  消费  ', class:'btn btn-success btn-large btn-primary' %>
			</div>
		</div>
		
	<% end %>
	
	<br />
	<br />
	
	<% if flash[:message] %>
	<% flash[:message].each do |key, value| %>
	<div class="alert alert-block alert-<%= key %>">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <strong><%= value %></strong>
	</div>
	<% end %>
	<% end %>
	
</div>